Feature/vdx 148/add verifier information for wallet clients
Sphereon-Opensource/did-auth-siop pull request #34
Opened 2022-09-28 10:38 UTC by hrehman-sphereon

2022-09-28 12:11 UTC, sksadjad requested changes
looks good to me, just something I forgot to mention yesterday, please add some assertion for the new added values in the RP and OP test suits

2022-09-29 09:52 UTC, hrehman-sphereon commented
> looks good to me, just something I forgot to mention yesterday, please add some assertion for the new added values in the RP and OP test suits

Some assertions added, for example, in the jest case 'return a reference url'

2022-09-29 20:49 UTC, nklomp commented
As mentioned in a comment I would expect a builder that has a seperate optional argument for a language tag and a required argument. The builder than builds the complete tags

2022-09-30 09:30 UTC, hrehman-sphereon commented
> As mentioned in a comment I would expect a builder that has a seperate optional argument for a language tag and a required argument. The builder than builds the complete tags

@nklomp 

test/IT.spec.ts
> 'RP and OP interaction should'   'succeed when calling each other in the full flow'
line 149.

From this same example we do allow user to set the variable. We do not have a builder method for eavery single field of the registration object. Would you like to have builder method for these 3 fields or all fields of registration ?

2022-09-30 09:34 UTC, hrehman-sphereon commented
> The builder than builds the complete tags

What does it mean ? we do not have field for every single language possible (cross product) and for every single field. So ... do we need to get rid of `[x: string]: any` and add fixed fields ? I hope this will be against the RFC as well as I don't think that's what you mean...

so, can you please explain ?

2022-10-03 10:04 UTC, sksadjad requested changes
added two small notes, otherwise looks good

2022-10-03 10:04 UTC, sksadjad commented on src/main/LanguageTagUtils.ts
> +  private static isStringNullOrEmpty(key: string) {
move this into `ObjectUtils`

2022-10-03 10:10 UTC, hrehman-sphereon commented on src/main/LanguageTagUtils.ts
> +export default class LanguageTagUtils {
fixed

2022-10-03 10:15 UTC, hrehman-sphereon commented on src/main/LanguageTagUtils.ts
> +  private static isStringNullOrEmpty(key: string) {
fixed

2022-10-03 11:58 UTC, sksadjad approved these changes
approved

2022-10-03 11:59 UTC, merged